modLoader = "javafml"
loaderVersion="[28,)"
license="Custom"
logoFile="pack.png"
logoBlur=false

[[mods]]
modId="moremobs"
version="1.5+mod"
displayName="More Mobs"
description='''Humanoid mobs get new variants through custom heads or through unused vanilla mobs! This pack uses §lover 85 custom player heads§r which can be obtained and placed in your world.
No Resource pack needed!

§lSupported Entities:§r Zombies, Husks, Drowned, Skeletons, Strays, Wither Skeletons, Mooshrooms, Piglins, Pillagers, Evokers and Vindicators

Execute the command §o/function §omore_mobs:settings§r for a world-specific settings menu and/or install MidnightLib for global settings accross all worlds.
'''
authors="Tschipcraft"
displayURL="https://linktr.ee/tschipcraft"
issueTrackerURL="https://github.com/Tschipcraft/more_mobs/issues"
updateJSONURL="https://api.modrinth.com/updates/HJR6V0I2/forge_updates.json"
displayTest="IGNORE_SERVER_VERSION"

[[dependencies.moremobs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moremobs]]
    modId="midnightlib"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"

[modproperties.moremobs]
    catalogueItemIcon="minecraft:player_head{SkullOwner:{Id:[I;-1813291128,-1535753890,-1791977748,-535107511],Properties:{textures:[{Value:\"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjA4MGRjOGJjYWQ4MjdhMzYzNThiMjRlMTIxODY5MzFiYTc1MjFlOTI0ZTEzMjFlZTFiY2ExNTg5YTUzYTRhZiJ9fX0=\"}]}}}"